AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

plugins:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['\s*#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/queue_schema.rb'
